./littleAdaParser < ./Test\ data/final/OK/ALLCAPS.ADA
./littleAdaParser < ./Test\ data/final/OK/BOOLVARS.ADA
./littleAdaParser < ./Test\ data/final/OK/CALLING.ADA
./littleAdaParser < ./Test\ data/final/OK/CASEDEMO.ADA
./littleAdaParser < ./Test\ data/final/OK/CASSE.ADA
./littleAdaParser < ./Test\ data/final/OK/COMMENTS.ADA
./littleAdaParser < ./Test\ data/final/OK/COMPARE.ADA
./littleAdaParser < ./Test\ data/final/OK/CONSTS.ADA
./littleAdaParser < ./Test\ data/final/OK/DUMBCONV.ADA
./littleAdaParser < ./Test\ data/final/OK/FUNCT.ADA
./littleAdaParser < ./Test\ data/final/OK/GOODFORM.ADA
./littleAdaParser < ./Test\ data/final/OK/GOTODEMO.ADA
./littleAdaParser < ./Test\ data/final/OK/IFDEMO.ADA
./littleAdaParser < ./Test\ data/final/OK/INITEX.ADA
./littleAdaParser < ./Test\ data/final/OK/LOOPDEMO.ADA
./littleAdaParser < ./Test\ data/final/OK/Main.ada
./littleAdaParser < ./Test\ data/final/OK/MOREINTS.ADA
./littleAdaParser < ./Test\ data/final/OK/NESTING.ADA
./littleAdaParser < ./Test\ data/final/OK/NOCAPS.ADA
./littleAdaParser < ./Test\ data/final/OK/ODDSQRE.ADA
./littleAdaParser < ./Test\ data/final/OK/ONEINT.ADA
./littleAdaParser < ./Test\ data/final/OK/ONELINE.ADA
./littleAdaParser < ./Test\ data/final/OK/PROCED1.ADA
./littleAdaParser < ./Test\ data/final/OK/PROCED2.ADA
./littleAdaParser < ./Test\ data/final/OK/PROCED3.ADA
./littleAdaParser < ./Test\ data/final/OK/SCOPE.ADA
./littleAdaParser < ./Test\ data/final/OK/SCOPE2.ADA
./littleAdaParser < ./Test\ data/final/OK/SOMEOUT.ADA
./littleAdaParser < ./Test\ data/final/OK/SUBTYPES.ADA
./littleAdaParser < ./Test\ data/final/OK/TEMPCONV.ADA
./littleAdaParser < ./Test\ data/final/OK/TRIVIAL.ADA
./littleAdaParser < ./Test\ data/final/OK/UGLYFORM.ADA
