typedef struct filee filee; // défini
typedef struct line line; // défini
typedef struct declaration declaration; // défini
typedef struct expression expression; // défini
typedef struct instruction instruction; // défini
typedef struct fonctionSpec fonctionSpec; // défini
typedef struct procedureSpec procedureSpec; // défini
typedef struct procedureDef procedureDef; // défini
typedef struct fonctionDef fonctionDef; // défini
typedef struct object object; // défini
typedef struct constante constante; // défini
typedef struct identif identif; // défini
typedef struct constanteBase constanteBase; // défini
typedef struct affectation affectation; // défini
typedef struct procedureCall procedureCall; // défini
typedef struct loop loop; // défini
typedef struct whileLoop whileLoop; // défini
typedef struct forLoop forLoop; // défini
typedef struct condition condition; // défini
typedef struct distCas distCas; // défini
typedef struct alternative alternative; // défini
typedef struct sortie sortie; // défini
typedef struct definition definition; // défini
typedef struct tupleChoix tupleChoix; // défini
typedef struct subtypeDec subtypeDec; // défini
typedef struct type type; // défini
typedef struct isRange isRange; // défini
typedef struct preExpression preExpression; // défini
typedef struct symboleExpressions symboleExpressions; // défini